# Archivo de configuracion para crear la instancion de flyway y mysql en un contenedor docker
version: '3'
services:
  flyway:
    image: flyway/flyway
    command: -connectRetries=60 migrate
    volumes:
      - ./migrate:/flyway/sql
      - ./conf:/flyway/conf
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_PORT: '${MYSQL_PORT}'
    depends_on:
      - database
  database:
    container_name: database
    image: mysql
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    expose:
      - "${MYSQL_PORT}"
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"